### ISSUE TITLE
scipy interpolation broken with version 1.10.0

### ISSUE THREAD

**Issue by w3168** [thwaitesproject/thwaites#4]
The latest version of scipy breaks the grid interpolation used for the isomip+ ice draft in the 3d simulation.
2d interpolations seem fine with 1.10.1. scipy version 1.9.1 seems fine with 3d... Here is the traceback. 

e.g. running ~/thwaites/run_scripts_testing/ice_shelf_cavity/isomip_plus: 
python isomip_plus_3d_extruded_layered.py 27.01.23 8000 15 6 1e-3 1 5e-5 900 90 90

Traceback (most recent call last):
  File "/home/wis15/thwaites/run_scripts_testing/ice_shelf_cavity/isomip_plus/isomip_plus_3d_extruded_layered.py", line 180, in <module>
    ice_draft_base = interpolate_data(ice_draft_file, P1)
  File "/home/wis15/thwaites/thwaites/interpolate.py", line 95, in interpolate
    q.dat.data[:] = _sample(f, X, method, y_transect)
  File "/home/wis15/thwaites/thwaites/interpolate.py", line 52, in _sample
    return interpolator(X, method=method)
  File "/home/wis15/firedrake/lib/python3.10/site-packages/scipy/interpolate/_rgi.py", line 331, in __call__
    indices, norm_distances = self._find_indices(xi.T)
  File "/home/wis15/firedrake/lib/python3.10/site-packages/scipy/interpolate/_rgi.py", line 499, in _find_indices
    return find_indices(self.grid, xi)
  File "_rgi_cython.pyx", line 75, in scipy.interpolate._rgi_cython.find_indices
  File "stringsource", line 660, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 350, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only

**Comment by w3168** [comment]
For now added a hack which forces the scipy version to be 1.9.1 until we get round to fixing it.

**Comment by w3168** [comment]
PR #6 seems to have removed the scipy requirement (by accident?) but testing the 3d isomipplus_layered bathymetry now seems to be working. 
running
```
pip freeze | grep scipy
scipy==1.13.0
```
so maybe this got fixed in a scipy release...
Anyway close this for now.
